version: '3.8'

services:
  postgres:
    image: postgres:17.4
    container_name: dishes-postgres
    environment:
      POSTGRES_USER: eva
      POSTGRES_PASSWORD: eva
      POSTGRES_DB: dishes
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
